# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='last_modified_time')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], max_length=1, verbose_name='status')),
                ('abstract', models.CharField(blank=True, help_text='you can choice fist 54 words as the abstruct', max_length=54, null=True, verbose_name='abstract')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='liskes')),
                ('topped', models.BooleanField(default=False, verbose_name='topped')),
            ],
            options={
                'ordering': ['-last_modified_time'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='last_modified_tiem')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category', verbose_name='category'),
        ),
    ]
