# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='user_name')),
                ('user_email', models.EmailField(max_length=255, verbose_name='user_email')),
                ('body', models.TextField(verbose_name='body')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='last_modified_time')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='文章创建时间'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='评论所属文章'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='tags'),
        ),
    ]
